CREATE TABLE IF NOT EXISTS country (
    `city` VARCHAR(16) CHARACTER SET utf8,
    `country` VARCHAR(16) CHARACTER SET utf8,
    `country_short` VARCHAR(3) CHARACTER SET utf8,
    `capital` VARCHAR(32) CHARACTER SET utf8
);
INSERT INTO country VALUES
    ('Tokyo','Japan','JPN','Tōkyō'),
    ('Jakarta','Indonesia','IDN','Jakarta'),
    ('Delhi','India','IND','Delhi'),
    ('Mumbai','India','IND','Mahārāshtra'),
    ('Manila','Philippines','PHL','Manila'),
    ('Shanghai','China','CHN','Shanghai'),
    ('Sao Paulo','Brazil','BRA','São Paulo'),
    ('Seoul','Korea, South','KOR','Seoul'),
    ('Mexico City','Mexico','MEX','Ciudad de México'),
    ('Guangzhou','China','CHN','Guangdong'),
    ('Beijing','China','CHN','Beijing'),
    ('Cairo','Egypt','EGY','Al Qāhirah'),
    ('New York','United States','USA','New York'),
    ('Kolkata','India','IND','West Bengal'),
    ('Moscow','Russia','RUS','Moskva'),
    ('Bangkok','Thailand','THA','Krung Thep Maha Nakhon'),
    ('Buenos Aires','Argentina','ARG','Buenos Aires, Ciudad Autónoma de'),
    ('Shenzhen','China','CHN','Guangdong'),
    ('Dhaka','Bangladesh','BGD','Dhaka'),
    ('Lagos','Nigeria','NGA','Lagos'),
    ('Istanbul','Turkey','TUR','İstanbul'),
    ('Osaka','Japan','JPN','Ōsaka'),
    ('Karachi','Pakistan','PAK','Sindh'),
    ('Bangalore','India','IND','Karnātaka'),
    ('Tehran','Iran','IRN','Tehrān'),
    ('Kinshasa','Congo (Kinshasa)','COD','Kinshasa'),
    ('Ho Chi Minh City','Vietnam','VNM','Hồ Chí Minh'),
    ('Los Angeles','United States','USA','California'),
    ('Rio de Janeiro','Brazil','BRA','Rio de Janeiro'),
    ('Nanyang','China','CHN','Henan'),
    ('Chennai','India','IND','Tamil Nādu'),
    ('Chengdu','China','CHN','Sichuan'),
    ('Lahore','Pakistan','PAK','Punjab'),
    ('Paris','France','FRA','Île-de-France'),
    ('London','United Kingdom','GBR','London, City of'),
    ('Linyi','China','CHN','Shandong'),
    ('Tianjin','China','CHN','Tianjin'),
    ('Shijiazhuang','China','CHN','Hebei'),
    ('Baoding','China','CHN','Hebei'),
    ('Zhoukou','China','CHN','Henan'),
    ('Lima','Peru','PER','Lima'),
    ('Hyderabad','India','IND','Telangana'),
    ('Bogota','Colombia','COL','Bogotá'),
    ('Weifang','China','CHN','Shandong'),
    ('Nagoya','Japan','JPN','Aichi'),
    ('Wuhan','China','CHN','Hubei'),
    ('Heze','China','CHN','Shandong'),
    ('Ganzhou','China','CHN','Jiangxi'),
    ('Tongshan','China','CHN','Jiangsu'),
    ('Chicago','United States','USA','Illinois'),
    ('Handan','China','CHN','Hebei'),
    ('Luanda','Angola','AGO','Luanda'),
    ('Fuyang','China','CHN','Anhui'),
    ('Kuala Lumpur','Malaysia','MYS','Kuala Lumpur'),
    ('Jining','China','CHN','Shandong'),
    ('Dongguan','China','CHN','Guangdong'),
    ('Hanoi','Vietnam','VNM','Hà Nội'),
    ('Pune','India','IND','Mahārāshtra'),
    ('Chongqing','China','CHN','Chongqing'),
    ('Changchun','China','CHN','Jilin'),
    ('Zhumadian','China','CHN','Henan'),
    ('Ningbo','China','CHN','Zhejiang'),
    ('Onitsha','Nigeria','NGA','Anambra'),
    ('Nanjing','China','CHN','Jiangsu'),
    ('Hefei','China','CHN','Anhui'),
    ('Ahmadabad','India','IND','Gujarāt'),
    ('Hong Kong','Hong Kong','HKG',NULL),
    ('Khartoum','Sudan','SDN','Khartoum'),
    ('Nantong','China','CHN','Jiangsu'),
    ('Yancheng','China','CHN','Jiangsu'),
    ('Foshan','China','CHN','Guangdong'),
    ('Nanning','China','CHN','Guangxi'),
    ('Hengyang','China','CHN','Hunan'),
    ('Xi''an','China','CHN','Shaanxi'),
    ('Shenyang','China','CHN','Liaoning'),
    ('Tangshan','China','CHN','Hebei'),
    ('Shaoyang','China','CHN','Hunan'),
    ('Changsha','China','CHN','Hunan'),
    ('Santiago','Chile','CHL','Región Metropolitana'),
    ('Zhengzhou','China','CHN','Henan'),
    ('Zhanjiang','China','CHN','Guangdong'),
    ('Riyadh','Saudi Arabia','SAU','Ar Riyāḑ'),
    ('Cangzhou','China','CHN','Hebei'),
    ('Dar es Salaam','Tanzania','TZA','Dar es Salaam'),
    ('Maoming','China','CHN','Guangdong'),
    ('Huanggang','China','CHN','Hubei'),
    ('Xinyang','China','CHN','Henan'),
    ('Shangrao','China','CHN','Jiangxi'),
    ('Luoyang','China','CHN','Henan'),
    ('Bijie','China','CHN','Guizhou'),
    ('Yantai','China','CHN','Shandong'),
    ('Quanzhou','China','CHN','Fujian'),
    ('Hangzhou','China','CHN','Zhejiang'),
    ('Miami','United States','USA','Florida'),
    ('Kunming','China','CHN','Yunnan'),
    ('Nanchong','China','CHN','Sichuan'),
    ('Zunyi','China','CHN','Guizhou'),
    ('Lu''an','China','CHN','Anhui'),
    ('Yichun','China','CHN','Jiangxi'),
    ('Taizhou','China','CHN','Zhejiang'),
    ('Liaocheng','China','CHN','Shandong'),
    ('Qujing','China','CHN','Yunnan'),
    ('Xiangyang','China','CHN','Hubei'),
    ('Surat','India','IND','Gujarāt'),
    ('Baghdad','Iraq','IRQ','Baghdād'),
    ('Qingdao','China','CHN','Shandong'),
    ('Singapore','Singapore','SGP','Central Singapore'),
    ('Dallas','United States','USA','Texas'),
    ('Changde','China','CHN','Hunan');
