USE android_application_database_internship;

CREATE TABLE jse_cf_languages (
  Languages_Id tinyint(4) NOT NULL,
  Languages_names varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT INTO jse_cf_languages (Languages_names) VALUES
(''),
('Adi'),
('Assamese'),
('Bengali'),
('Bhojpuri'),
('Bhutia'),
('Bodo'),
('Dogri'),
('Garo'),
('Gujrati'),
('Hindi'),
('Kannada'),
('Kashmiri'),
('Khasi'),
('Konkani'),
('Lambadi'),
('Lepcha'),
('Maithili'),
('Malayalam'),
('Manipuri'),
('Marathi'),
('Marwari'),
('Mizo'),
('Nagamese'),
('Nepalese'),
('Nishing'),
('Oriya'),
('Pahari'),
('Punjabi'),
('Rajasthani'),
('Sanskrit'),
('Sikkimese'),
('Sindhi'),
('Tamil'),
('Telugu'),
('Tenyidie(Angami)'),
('Tibetan'),
('Tulu'),
('Urdu'),
('Arabic'),
('Chinese'),
('Creole'),
('English'),
('French'),
('German'),
('Hausa'),
('Italian'),
('Japaanese'),
('Persian'),
('Portugese'),
('Russian'),
('Spanish'),
('N.A.');
