SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Afghanistan" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Albania" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Algeria" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "American Samoa" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Andorra" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Angola" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Antigua And Barbuda" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Argentina" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Armenia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Aruba" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Australia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Austria" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Azerbaijan" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Bahamas, The" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Bahrain" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Bangladesh" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Barbados" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Belarus" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Belgium" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Belize" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Benin" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Bermuda" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Bhutan" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Bolivia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Bosnia And Herzegovina" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Botswana" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Brazil" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Brunei" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Bulgaria" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Burkina Faso" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Burma" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Burundi" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "C?te D?Ivoire" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Cabo Verde" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Cambodia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Cameroon" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Canada" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Cayman Islands" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Central African Republic" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Chad" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Chile" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "China" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Colombia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Comoros" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Congo (Brazzaville)" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Congo (Kinshasa)" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Cook Islands" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Costa Rica" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Croatia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Cuba" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Cura?ao" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Cyprus" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Czechia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Denmark" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Djibouti" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Dominica" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Dominican Republic" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Ecuador" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Egypt" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "El Salvador" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Equatorial Guinea" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Eritrea" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Estonia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Ethiopia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Falkland Islands (Islas Malvinas)" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Faroe Islands" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Fiji" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Finland" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "France" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "French Guiana" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "French Polynesia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Gabon" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Gambia, The" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Georgia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Germany" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Ghana" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Gibraltar" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Greece" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Greenland" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Grenada" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Guadeloupe" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Guam" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Guatemala" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Guinea" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Guinea-Bissau" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Guyana" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Haiti" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Honduras" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Hong Kong" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Hungary" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Iceland" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "India" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Indonesia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Iran" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Iraq" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Ireland" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Isle Of Man" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Israel" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Italy" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Jamaica" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Japan" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Jersey" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Jordan" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Kazakhstan" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Kenya" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Kiribati" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Korea, North" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Korea, South" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Kosovo" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Kuwait" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Kyrgyzstan" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Laos" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Latvia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Lebanon" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Lesotho" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Liberia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Libya" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Liechtenstein" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Lithuania" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Luxembourg" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Macau" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Macedonia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Madagascar" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Malawi" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Malaysia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Maldives" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Mali" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Malta" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Marshall Islands" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Martinique" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Mauritania" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Mauritius" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Mayotte" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Mexico" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Micronesia, Federated States Of" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Moldova" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Monaco" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Mongolia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Montenegro" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Morocco" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Mozambique" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Namibia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Nepal" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Netherlands" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "New Caledonia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "New Zealand" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Nicaragua" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Niger" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Nigeria" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Northern Mariana Islands" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Norway" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Oman" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Pakistan" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Palau" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Panama" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Papua New Guinea" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Paraguay" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Peru" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Philippines" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Poland" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Portugal" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Puerto Rico" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Qatar" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Reunion" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Romania" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Russia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Rwanda" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Saint Helena, Ascension, And Tristan Da Cunha" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Saint Kitts And Nevis" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Saint Lucia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Saint Vincent And The Grenadines" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Samoa" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "San Marino" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Sao Tome And Principe" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Saudi Arabia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Senegal" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Serbia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Seychelles" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Sierra Leone" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Singapore" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Slovakia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Slovenia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Solomon Islands" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Somalia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "South Africa" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "South Georgia And South Sandwich Islands" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "South Sudan" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Spain" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Sri Lanka" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Sudan" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Suriname" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Swaziland" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Sweden" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Switzerland" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Syria" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Taiwan" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Tajikistan" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Tanzania" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Thailand" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Timor-Leste" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Togo" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Tonga" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Trinidad And Tobago" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Tunisia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Turkey" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Turkmenistan" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Turks And Caicos Islands" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Tuvalu" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Uganda" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Ukraine" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "United Arab Emirates" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "United Kingdom" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "United States" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Uruguay" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Uzbekistan" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Vanuatu" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Vatican City" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Venezuela" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Vietnam" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Wallis And Futuna" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "West Bank" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Yemen" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Zambia" ORDER BY capital ASC;
SELECT DISTINCT capital AS States FROM admin_user_resident_basic_info WHERE 1 = 1 AND country = "Zimbabwe" ORDER BY capital ASC;






public static String AdminUserStatesOfCountryAfghanistan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Afghanistan";
public static String AdminUserStatesOfCountryAlbania = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Albania";
public static String AdminUserStatesOfCountryAlgeria = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Algeria";
public static String AdminUserStatesOfCountryAmericanSamoa = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=American Samoa";
public static String AdminUserStatesOfCountryAndorra = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Andorra";
public static String AdminUserStatesOfCountryAngola = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Angola";
public static String AdminUserStatesOfCountryAntiguaAndBarbuda = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Antigua And Barbuda";
public static String AdminUserStatesOfCountryArgentina = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Argentina";
public static String AdminUserStatesOfCountryArmenia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Armenia";
public static String AdminUserStatesOfCountryAruba = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Aruba";
public static String AdminUserStatesOfCountryAustralia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Australia";
public static String AdminUserStatesOfCountryAustria = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Austria";
public static String AdminUserStatesOfCountryAzerbaijan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Azerbaijan";
public static String AdminUserStatesOfCountryBahamasThe = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Bahamas, The";
public static String AdminUserStatesOfCountryBahrain = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Bahrain";
public static String AdminUserStatesOfCountryBangladesh = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Bangladesh";
public static String AdminUserStatesOfCountryBarbados = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Barbados";
public static String AdminUserStatesOfCountryBelarus = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Belarus";
public static String AdminUserStatesOfCountryBelgium = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Belgium";
public static String AdminUserStatesOfCountryBelize = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Belize";
public static String AdminUserStatesOfCountryBenin = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Benin";
public static String AdminUserStatesOfCountryBermuda = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Bermuda";
public static String AdminUserStatesOfCountryBhutan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Bhutan";
public static String AdminUserStatesOfCountryBolivia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Bolivia";
public static String AdminUserStatesOfCountryBosniaAndHerzegovina = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Bosnia And Herzegovina";
public static String AdminUserStatesOfCountryBotswana = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Botswana";
public static String AdminUserStatesOfCountryBrazil = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Brazil";
public static String AdminUserStatesOfCountryBrunei = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Brunei";
public static String AdminUserStatesOfCountryBulgaria = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Bulgaria";
public static String AdminUserStatesOfCountryBurkinaFaso = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Burkina Faso";
public static String AdminUserStatesOfCountryBurma = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Burma";
public static String AdminUserStatesOfCountryBurundi = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Burundi";
public static String AdminUserStatesOfCountryC?teD?Ivoire = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=C?te D?Ivoire";
public static String AdminUserStatesOfCountryCabo = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Cabo Verde";
public static String AdminUserStatesOfCountryCambodia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Cambodia";
public static String AdminUserStatesOfCountryCameroon = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Cameroon";
public static String AdminUserStatesOfCountryCanada = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Canada";
public static String AdminUserStatesOfCountryCaymanIslands = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Cayman Islands";
public static String AdminUserStatesOfCountryCentralAfricanRepublic = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Central African Republic";
public static String AdminUserStatesOfCountryChad = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Chad";
public static String AdminUserStatesOfCountryChile = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Chile";
public static String AdminUserStatesOfCountryChina = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=China";
public static String AdminUserStatesOfCountryColombia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Colombia";
public static String AdminUserStatesOfCountryComoros = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Comoros";
public static String AdminUserStatesOfCountryCongo(Brazzaville) = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Congo (Brazzaville)";
public static String AdminUserStatesOfCountryCongo(Kinshasa) = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Congo (Kinshasa)";
public static String AdminUserStatesOfCountryCookIslands = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Cook Islands";
public static String AdminUserStatesOfCountryCostaRica = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Costa Rica";
public static String AdminUserStatesOfCountryCroatia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Croatia";
public static String AdminUserStatesOfCountryCuba = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Cuba";
public static String AdminUserStatesOfCountryCura?ao = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Cura?ao";
public static String AdminUserStatesOfCountryCyprus = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Cyprus";
public static String AdminUserStatesOfCountryCzechia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Czechia";
public static String AdminUserStatesOfCountryDenmark = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Denmark";
public static String AdminUserStatesOfCountryDjibouti = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Djibouti";
public static String AdminUserStatesOfCountryDominica = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Dominica";
public static String AdminUserStatesOfCountryDominicanRepublic = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Dominican Republic";
public static String AdminUserStatesOfCountryEcuador = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Ecuador";
public static String AdminUserStatesOfCountryEgypt = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Egypt";
public static String AdminUserStatesOfCountryElSalvador = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=El Salvador";
public static String AdminUserStatesOfCountryEquatorialGuinea = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Equatorial Guinea";
public static String AdminUserStatesOfCountryEritrea = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Eritrea";
public static String AdminUserStatesOfCountryEstonia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Estonia";
public static String AdminUserStatesOfCountryEthiopia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Ethiopia";
public static String AdminUserStatesOfCountryFalklandIslands(Islas Malvinas) = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Falkland Islands (Islas Malvinas)";
public static String AdminUserStatesOfCountryFaroeIslands = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Faroe Islands";
public static String AdminUserStatesOfCountryFiji = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Fiji";
public static String AdminUserStatesOfCountryFinland = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Finland";
public static String AdminUserStatesOfCountryFrance = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=France";
public static String AdminUserStatesOfCountryFrenchGuiana = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=French Guiana";
public static String AdminUserStatesOfCountryFrenchPolynesia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=French Polynesia";
public static String AdminUserStatesOfCountryGabon = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Gabon";
public static String AdminUserStatesOfCountryGambiaThe = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Gambia, The";
public static String AdminUserStatesOfCountryGeorgia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Georgia";
public static String AdminUserStatesOfCountryGermany = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Germany";
public static String AdminUserStatesOfCountryGhana = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Ghana";
public static String AdminUserStatesOfCountryGibraltar = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Gibraltar";
public static String AdminUserStatesOfCountryGreece = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Greece";
public static String AdminUserStatesOfCountryGreenland = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Greenland";
public static String AdminUserStatesOfCountryGrenada = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Grenada";
public static String AdminUserStatesOfCountryGuadeloupe = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Guadeloupe";
public static String AdminUserStatesOfCountryGuam = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Guam";
public static String AdminUserStatesOfCountryGuatemala = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Guatemala";
public static String AdminUserStatesOfCountryGuinea = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Guinea";
public static String AdminUserStatesOfCountryGuineaBissau = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Guinea-Bissau";
public static String AdminUserStatesOfCountryGuyana = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Guyana";
public static String AdminUserStatesOfCountryHaiti = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Haiti";
public static String AdminUserStatesOfCountryHonduras = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Honduras";
public static String AdminUserStatesOfCountryHongKong = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Hong Kong";
public static String AdminUserStatesOfCountryHungary = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Hungary";
public static String AdminUserStatesOfCountryIceland = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Iceland";
public static String AdminUserStatesOfCountryIndia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=India";
public static String AdminUserStatesOfCountryIndonesia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Indonesia";
public static String AdminUserStatesOfCountryIran = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Iran";
public static String AdminUserStatesOfCountryIraq = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Iraq";
public static String AdminUserStatesOfCountryIreland = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Ireland";
public static String AdminUserStatesOfCountryIsleIsleOfMan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Isle Of Man";
public static String AdminUserStatesOfCountryIsrael = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Israel";
public static String AdminUserStatesOfCountryItaly = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Italy";
public static String AdminUserStatesOfCountryJamaica = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Jamaica";
public static String AdminUserStatesOfCountryJapan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Japan";
public static String AdminUserStatesOfCountryJersey = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Jersey";
public static String AdminUserStatesOfCountryJordan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Jordan";
public static String AdminUserStatesOfCountryKazakhstan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Kazakhstan";
public static String AdminUserStatesOfCountryKenya = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Kenya";
public static String AdminUserStatesOfCountryKiribati = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Kiribati";
public static String AdminUserStatesOfCountryKoreaNorth = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Korea, North";
public static String AdminUserStatesOfCountryKoreaSouth = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Korea, South";
public static String AdminUserStatesOfCountryKosovo = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Kosovo";
public static String AdminUserStatesOfCountryKuwait = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Kuwait";
public static String AdminUserStatesOfCountryKyrgyzstan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Kyrgyzstan";
public static String AdminUserStatesOfCountryLaos = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Laos";
public static String AdminUserStatesOfCountryLatvia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Latvia";
public static String AdminUserStatesOfCountryLebanon = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Lebanon";
public static String AdminUserStatesOfCountryLesotho = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Lesotho";
public static String AdminUserStatesOfCountryLiberia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Liberia";
public static String AdminUserStatesOfCountryLibya = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Libya";
public static String AdminUserStatesOfCountryLiechtenstein = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Liechtenstein";
public static String AdminUserStatesOfCountryLithuania = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Lithuania";
public static String AdminUserStatesOfCountryLuxembourg = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Luxembourg";
public static String AdminUserStatesOfCountryMacau = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Macau";
public static String AdminUserStatesOfCountryMacedonia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Macedonia";
public static String AdminUserStatesOfCountryMadagascar = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Madagascar";
public static String AdminUserStatesOfCountryMalawi = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Malawi";
public static String AdminUserStatesOfCountryMalaysia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Malaysia";
public static String AdminUserStatesOfCountryMaldives = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Maldives";
public static String AdminUserStatesOfCountryMali = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Mali";
public static String AdminUserStatesOfCountryMalta = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Malta";
public static String AdminUserStatesOfCountryMarshallIslands = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Marshall Islands";
public static String AdminUserStatesOfCountryMartinique = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Martinique";
public static String AdminUserStatesOfCountryMauritania = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Mauritania";
public static String AdminUserStatesOfCountryMauritius = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Mauritius";
public static String AdminUserStatesOfCountryMayotte = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Mayotte";
public static String AdminUserStatesOfCountryMexico = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Mexico";
public static String AdminUserStatesOfCountryMicronesiaFederatedStatesOf = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Micronesia, Federated States Of";
public static String AdminUserStatesOfCountryMoldova = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Moldova";
public static String AdminUserStatesOfCountryMonaco = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Monaco";
public static String AdminUserStatesOfCountryMongolia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Mongolia";
public static String AdminUserStatesOfCountryMontenegro = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Montenegro";
public static String AdminUserStatesOfCountryMorocco = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Morocco";
public static String AdminUserStatesOfCountryMozambique = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Mozambique";
public static String AdminUserStatesOfCountryNamibia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Namibia";
public static String AdminUserStatesOfCountryNepal = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Nepal";
public static String AdminUserStatesOfCountryNetherlands = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Netherlands";
public static String AdminUserStatesOfCountryNewCaledonia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=New Caledonia";
public static String AdminUserStatesOfCountryNewZealand = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=New Zealand";
public static String AdminUserStatesOfCountryNicaragua = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Nicaragua";
public static String AdminUserStatesOfCountryNiger = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Niger";
public static String AdminUserStatesOfCountryNigeria = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Nigeria";
public static String AdminUserStatesOfCountryNorthernMarianaIslands = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Northern Mariana Islands";
public static String AdminUserStatesOfCountryNorway = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Norway";
public static String AdminUserStatesOfCountryOman = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Oman";
public static String AdminUserStatesOfCountryPakistan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Pakistan";
public static String AdminUserStatesOfCountryPalau = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Palau";
public static String AdminUserStatesOfCountryPanama = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Panama";
public static String AdminUserStatesOfCountryPapuaNewGuinea = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Papua New Guinea";
public static String AdminUserStatesOfCountryParaguay = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Paraguay";
public static String AdminUserStatesOfCountryPeru = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Peru";
public static String AdminUserStatesOfCountryPhilippines = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Philippines";
public static String AdminUserStatesOfCountryPoland = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Poland";
public static String AdminUserStatesOfCountryPortugal = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Portugal";
public static String AdminUserStatesOfCountryPuertoRico = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Puerto Rico";
public static String AdminUserStatesOfCountryQatar = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Qatar";
public static String AdminUserStatesOfCountryReunion = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Reunion";
public static String AdminUserStatesOfCountryRomania = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Romania";
public static String AdminUserStatesOfCountryRussia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Russia";
public static String AdminUserStatesOfCountryRwanda = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Rwanda";
public static String AdminUserStatesOfCountrySaintHelenaAscensionAndTristanDaCunha = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Saint Helena, Ascension, And Tristan Da Cunha";
public static String AdminUserStatesOfCountrySaintKittsAndNevis = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Saint Kitts And Nevis";
public static String AdminUserStatesOfCountrySaintLucia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Saint Lucia";
public static String AdminUserStatesOfCountrySaintVincentAndTheGrenadines = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Saint Vincent And The Grenadines";
public static String AdminUserStatesOfCountrySamoa = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Samoa";
public static String AdminUserStatesOfCountrySanMarino = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=San Marino";
public static String AdminUserStatesOfCountrySaoTomeAndPrincipe = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Sao Tome And Principe";
public static String AdminUserStatesOfCountrySaudiArabia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Saudi Arabia";
public static String AdminUserStatesOfCountrySenegal = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Senegal";
public static String AdminUserStatesOfCountrySerbia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Serbia";
public static String AdminUserStatesOfCountrySeychelles = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Seychelles";
public static String AdminUserStatesOfCountrySierraLeone = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Sierra Leone";
public static String AdminUserStatesOfCountrySingapore = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Singapore";
public static String AdminUserStatesOfCountrySlovakia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Slovakia";
public static String AdminUserStatesOfCountrySlovenia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Slovenia";
public static String AdminUserStatesOfCountrySolomonIslands = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Solomon Islands";
public static String AdminUserStatesOfCountrySomalia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Somalia";
public static String AdminUserStatesOfCountrySouthAfrica = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=South Africa";
public static String AdminUserStatesOfCountrySouthGeorgiaAndSouthSandwichIslands = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=South Georgia And South Sandwich Islands";
public static String AdminUserStatesOfCountrySouthSudan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=South Sudan";
public static String AdminUserStatesOfCountrySpain = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Spain";
public static String AdminUserStatesOfCountrySriLanka = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Sri Lanka";
public static String AdminUserStatesOfCountrySudan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Sudan";
public static String AdminUserStatesOfCountrySuriname = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Suriname";
public static String AdminUserStatesOfCountrySwaziland = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Swaziland";
public static String AdminUserStatesOfCountrySweden = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Sweden";
public static String AdminUserStatesOfCountrySwitzerland = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Switzerland";
public static String AdminUserStatesOfCountrySyria = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Syria";
public static String AdminUserStatesOfCountryTaiwan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Taiwan";
public static String AdminUserStatesOfCountryTajikistan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Tajikistan";
public static String AdminUserStatesOfCountryTanzania = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Tanzania";
public static String AdminUserStatesOfCountryThailand = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Thailand";
public static String AdminUserStatesOfCountryTimorLeste = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Timor-Leste";
public static String AdminUserStatesOfCountryTogo = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Togo";
public static String AdminUserStatesOfCountryTonga = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Tonga";
public static String AdminUserStatesOfCountryTrinidadAndTobago = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Trinidad And Tobago";
public static String AdminUserStatesOfCountryTunisia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Tunisia";
public static String AdminUserStatesOfCountryTurkey = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Turkey";
public static String AdminUserStatesOfCountryTurkmenistan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Turkmenistan";
public static String AdminUserStatesOfCountryTurksAndCaicosIslands = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Turks And Caicos Islands";
public static String AdminUserStatesOfCountryTuvalu = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Tuvalu";
public static String AdminUserStatesOfCountryUganda = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Uganda";
public static String AdminUserStatesOfCountryUkraine = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Ukraine";
public static String AdminUserStatesOfCountryUnitedArabEmirates = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=United Arab Emirates";
public static String AdminUserStatesOfCountryUnitedKingdom = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=United Kingdom";
public static String AdminUserStatesOfCountryUnitedStates = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=United States";
public static String AdminUserStatesOfCountryUruguay = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Uruguay";
public static String AdminUserStatesOfCountryUzbekistan = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Uzbekistan";
public static String AdminUserStatesOfCountryVanuatu = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Vanuatu";
public static String AdminUserStatesOfCountryVaticanCity = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Vatican City";
public static String AdminUserStatesOfCountryVenezuela = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Venezuela";
public static String AdminUserStatesOfCountryVietnam = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Vietnam";
public static String AdminUserStatesOfCountryWallisAndFutuna = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Wallis And Futuna";
public static String AdminUserStatesOfCountryWestBank = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=West Bank";
public static String AdminUserStatesOfCountryYemen = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Yemen";
public static String AdminUserStatesOfCountryZambia = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Zambia";
public static String AdminUserStatesOfCountryZimbabwe = "http://192.168.1.104:81/Android_Application_Online_Api_fetch/Admin_User_Country_States_CityFetch_Api/Admin_User_Country_States_City_db_display_States.php?country=Zimbabwe";


if(AdminUserCountry.contains("India"))
{
	//
}
if(Zimbabwe